### ISSUE TITLE
Voting doesn't work

### ISSUE THREAD

**Issue by pelletiermaxime** [howtographql/vue-apollo#2]
I get the error

errorHandling.js?e4be:7 Error: Can't find field allLinks({}) on object (ROOT_QUERY) {
  "allLinks({\"first\":5,\"skip\":5,\"orderBy\":\"createdAt_DESC\"})": [

It worked fine before the pagination step, but I haven't figured yet what's the problem.

Thanks!

**Comment by Matt-Dionis** [comment]
Are you associating variables with the `ALL_LINKS_QUERY`? Check out this thread, may be the same issue: https://github.com/howtographql/howtographql/issues/236

**Comment by pelletiermaxime** [comment]
Yep, that fixes it! 
Both the tutorial and this repo should be updated. I can send a PR for this repo, but I don't know how to update the tutorial.

**Comment by Matt-Dionis** [comment]
@pelletiermaxime Awesome. Yeah, feel free to post a PR here to fix this repo. If you want, it may be nice to pull `LINKS_PER_PAGE` in from the constants file rather than hard-coding to 5 and use the current page number (accessed through route params) to set `skip` rather than hard-coding. Let me know if you have any questions and thanks again! I'll take care of updating the tutorial accordingly once your fix here lands.
